import type { Polygon } from 'geojson';

/** Developments with their units ("espelho de vendas 3D"), from public/data/developments.json. */

export type DevStage = 'launch' | 'construction' | 'ready';
export type LevelUse = 'lobby' | 'garage' | 'leisure' | 'residential';
export type UnitStatus = 'available' | 'reserved' | 'sold';

export interface Unit {
  id: string;
  /** Floor + final, e.g. "1502". */
  number: string;
  final: number;
  plan: string;
  areaM2: number;
  bedrooms: number;
  suites: number;
  parkingSpots: number;
  /** Index into `Development.shapes`. */
  shape: number;
  /** Grid positions the unit takes on its floor (2 for a penthouse spanning two). */
  cells: number;
  /** Illustrative only. */
  price: number;
  /** Fictional. */
  status: UnitStatus;
}

export interface Level {
  level: number;
  use: LevelUse;
  /** Metres above ground. */
  base: number;
  top: number;
  units: Unit[];
}

export interface Development {
  id: string;
  name: string;
  developer: string;
  address: string;
  location: [number, number];
  locationNote: string;
  stage: DevStage;
  delivery: string;
  floorHeightM: number;
  /** Public information, as published by the developer or the press. */
  facts: string[];
  /** What the demo estimates (not published). */
  estimates: string[];
  sources: { label: string; url: string }[];
  footprint: Polygon;
  center: [number, number];
  grid: { cols: number; rows: number };
  /** Unit outlines on a floor; `facing` = bearing (° clockwise from north) the unit looks towards. */
  shapes: { polygon: Polygon; facing: number }[];
  /** OSM buildings on the plot (assumed demolished for the tower). */
  hiddenBuildingIds: string[];
  levels: Level[];
}

export interface DevelopmentsFile {
  notice: string;
  developments: Development[];
}

export const STAGE_LABELS: Record<DevStage, string> = {
  launch: 'Lançamento',
  construction: 'Em obras',
  ready: 'Pronto',
};

export const UNIT_STATUS_LABELS: Record<UnitStatus, string> = {
  available: 'Disponível',
  reserved: 'Reservado',
  sold: 'Vendido',
};

export const LEVEL_USE_LABELS: Record<LevelUse, string> = {
  lobby: 'Térreo',
  garage: 'Garagem',
  leisure: 'Lazer',
  residential: 'Apartamentos',
};

export const allUnits = (d: Development): Unit[] => d.levels.flatMap((l) => l.units);
export const levelOf = (d: Development, unitId: string): Level | undefined =>
  d.levels.find((l) => l.units.some((u) => u.id === unitId));

export function countByStatus(d: Development): Record<UnitStatus, number> {
  const out: Record<UnitStatus, number> = { available: 0, reserved: 0, sold: 0 };
  for (const u of allUnits(d)) out[u.status]++;
  return out;
}

const COMPASS = ['Norte', 'Nordeste', 'Leste', 'Sudeste', 'Sul', 'Sudoeste', 'Oeste', 'Noroeste'] as const;
/** Southern hemisphere: the sun crosses the north; east gets the morning, west the afternoon. */
const SUN_HINTS: Record<(typeof COMPASS)[number], string> = {
  Norte: 'sol durante boa parte do dia',
  Nordeste: 'sol da manhã até o início da tarde',
  Leste: 'sol da manhã',
  Sudeste: 'sol só no início da manhã',
  Sul: 'pouco sol direto',
  Sudoeste: 'sol só no fim da tarde',
  Oeste: 'sol da tarde',
  Noroeste: 'sol do fim da manhã até a tarde',
};

/** "Leste", "sol da manhã" for a facing bearing in degrees. */
export function facingInfo(bearing: number): { direction: string; sun: string } {
  const i = Math.round((((bearing % 360) + 360) % 360) / 45) % 8;
  const direction = COMPASS[i];
  return { direction, sun: SUN_HINTS[direction] };
}

/** Light validation: the file is generated by scripts/generate-developments.mjs. */
export function validateDevelopmentsFile(raw: unknown): DevelopmentsFile {
  const f = raw as DevelopmentsFile;
  if (!f || !Array.isArray(f.developments)) throw new Error('developments.json: developments must be an array');
  for (const d of f.developments) {
    if (!d.id || !d.footprint || !Array.isArray(d.levels) || !Array.isArray(d.shapes))
      throw new Error(`developments.json: invalid development ${d.id ?? '?'}`);
    for (const u of allUnits(d)) if (!d.shapes[u.shape]) throw new Error(`developments.json: ${u.id} has no shape`);
  }
  return f;
}
